version: "3.9"

services:
  auth-service:
    build: ./cordillera-auth-service
    container_name: cordillera-auth-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_AUTH}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8083:8083"

  kpi-service:
    build: ./cordillera-kpi-service
    container_name: cordillera-kpi-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_KPI}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8082:8082"

  report-service:
    build: ./cordillera-report-service
    container_name: cordillera-report-service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL_REPORT}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"

  bff:
    build: ./cordillera-bff
    container_name: cordillera-bff
    restart: always
    depends_on:
      - auth-service
      - kpi-service
      - report-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8083/auth
      KPI_SERVICE_URL: http://kpi-service:8082/api/kpis
      REPORT_SERVICE_URL: http://report-service:8081/api/reports
    ports:
      - "8080:8080"

  frontend:
    build: ./cordillera-kpi-dashboard
    container_name: cordillera-kpi-dashboard
    restart: always
    depends_on:
      - bff
    ports:
      - "5173:80"